# -*- coding: utf-8 -*-
"""Tensorflow_implementation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1he0tWNzaogDKLsOrh1iF8y3WEbYLhr73
"""

import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

data = keras.datasets.fashion_mnist
(train_images, train_labels),(test_images,test_labels)=data.load_data()
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']
#print(train_labels[6])
#print(train_images[6])
train_images=train_images/255.0
test_images=test_images/255.0
# print(train_images[4])

model= keras.Sequential([
                         keras.layers.Flatten(input_shape=(28,28)),
                         keras.layers.Dense(128,activation="relu"),
                         keras.layers.Dense(10,activation="softmax")

])
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])
model.fit(train_images,train_labels,epochs=5)
print(".....Testing the data set ......")
# test_loss , test_acc = model.evaluate(test_images,test_labels)
# print("Tested Accuracy is :",test_acc)
# print(".....................")

"""# Now comes Prediction
 
"""

prediction = model.predict(test_images)

for i in range(5):
  plt.grid(False)
  plt.imshow(test_images[i], cmap=plt.cm.binary)
  plt.xlabel("Actual: "+ class_names[test_labels[i]])
  plt.title("Prediction" + class_names[np.argmax(prediction[i])])
  plt.show()

